[project]
name = "app-nat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "fastapi>=0.141.1",
    "psycopg2>=2.9.12",
    "pyfiglet>=1.0.4",
    "requests>=2.34.2",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.4",
]

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "ruff>=0.16.4",
]

[tool.ruff.lint]
select = [
    "E",   # pycodestyle (erreurs)
    "W",   # pycodestyle (warnings)
    "F",   # Pyflakes
    "I",   # isort (tri des imports)
    "N",   # pep8-naming
    "UP",  # pyupgrade (syntaxe moderne)
    "B",   # flake8-bugbear (bugs fréquents / mauvaises pratiques)
    "C4",  # flake8-comprehensions
    "SIM", # flake8-simplify
    "TID", # flake8-tidy-imports
    "RUF", # règles spécifiques à Ruff
]

ignore = [
    "E501",  # ligne trop longue (géré par le formatter)
    "B008"
]
